# Generated by Django 3.0 on 2019-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20160315_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalelection',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
