# Generated by Django 3.0 on 2019-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20160312_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoteipmap',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
